terraform destroy if any failure

diff --git a/.github/workflows/deploy-serverless.yml b/.github/workflows/deploy-serverless.yml
--- a/.github/workflows/deploy-serverless.yml
+++ b/.github/workflows/deploy-serverless.yml
@@ -79,4 +79,10 @@ jobs:
         run: terraform plan
 
       - name: Terraform Apply
-        run: terraform apply -auto-approve
+        run: |
+          terraform apply -auto-approve
+          if [ $? -ne 0 ]; then
+            echo "Terraform apply failed, destroying resources"
+            terraform destroy -auto-approve
+            exit 1
+          fi
